### ISSUE TITLE
关于使用泛型后无法根据分组进行分类显示的问题

### ISSUE THREAD

**Issue by yoin528** [JYHarvest/springfox3-plus#2]
1、我在做springmvc时需要统一的结果输出，此时用到了泛型，同时分页的数据也使用的泛型，这就导致了在过滤分组时无法使用Schema替换ref的方式，感觉使用过滤的方案有些问题，还是觉得在事前使用类似@JsonView的方式会好一些，但这方面的资料比较少，需要查下源码
2、后面会根据注解的分组信息，在@RestController时，将Json数据根据分组进行请求注入和响应输出的序列化和反序列化，这个使用阿里的Fastjson2可以做到。
       目前就使用泛型来说，感觉事后过滤的方案可能需要兼容的场景太多了，无法做到面面俱到，事前这个方案暂时还在查找，如果这个能做到，在框架上就减少非常多的DTO，VO的转换，不知道你是否遇到这个问题？

**Comment by JYHarvest** [comment]
具体代码贴一下呢？写个demo也行，之前我没用过

**Comment by JYHarvest** [comment]
可以一起研究一下

**Comment by yoin528** [comment]
> 具体代码贴一下呢？写个demo也行，之前我没用过

这是父类，做通用增删改查用的
```java
package com.littora.basic.model;

import com.baomidou.mybatisplus.annotation.*;
import com.littora.basic.model.group.annotation.ApiModelGroup;
import com.littora.basic.model.pojo.PageParam;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

@Data
public class BaseModel<ID extends Serializable> implements GenericTypeHelper,Serializable {
    /**
     * 主键
     */
    @TableId
    @ApiModelGroup({"read","modify","delete"})
//    @ApiModelProperty(value = "主键ID", example = "1")
    @Schema(description="主键ID")
    protected ID id;// 禁止使用0作为主键
    /**
     * 多租户编号
     */
    @TableField(fill = FieldFill.INSERT)
    @ApiModelGroup({"read","modify","delete"})
//    @ApiModelProperty(value = "租户ID", example = "1")
    @Schema(description="租户ID")
    protected ID tenantId;
    /**
     * 创建者，目前使用 SysUser 的 id 编号
     */
    @TableField(fill = FieldFill.INSERT)
    @ApiModelGroup({"creater"})
//    @ApiModelProperty(value = "创建者ID")
    @Schema(description="创建者ID")
    protected ID creator;
    /**
     * 创建时间
     */
    @TableField(fill = FieldFill.INSERT)
    @ApiModelGroup({"creater"})
//    @ApiModelProperty(value = "创建时间")
    @Schema(description="创建时间")
    protected LocalDateTime createTime;
    /**
     * 更新者，目前使用 SysUser 的 id 编号
     */
    @TableField(fill = FieldFill.INSERT_UPDATE)
    @ApiModelGroup({"updater"})
//    @ApiModelProperty(value = "修改者")
    @Schema(description="修改者")
    protected ID updater;
    /**
     * 最后更新时间
     */
    @TableField(fill = FieldFill.INSERT_UPDATE)
    @ApiModelGroup({"updater"})
//    @ApiModelProperty(value = "修改时间")
    @Schema(description="修改时间")
    protected LocalDateTime updateTime;
    /**
     * 数据版本,用于乐观锁
     **/
    @TableField
    @Version
    @ApiModelGroup({"version"})
//    @ApiModelProperty(value = "数据版本")
    @Schema(description="数据版本",hidden = true)
    protected Long dataVersion;
    /**
     * 是否删除
     */
    @TableLogic
    @ApiModelGroup({"deleted"})
//    @ApiModelProperty(value = "逻辑删除标志，0：逻辑未删除，1：逻辑已删除")
    @Schema(description="逻辑删除标志",hidden = true)
    protected Boolean deleted = false;
    /**
     * 分页对象，不入库
     **/
    @TableField(exist = false)
    @ApiModelGroup({"page"})
//    @ApiModelProperty(value = "分页参数")
    @Schema(description="分页参数")
    protected PageParam pageParam;
    /**
     * 当前操作上下文，不入库
     **/
    @TableField(exist = false)
    @ApiModelGroup({"context"})
    @Schema(hidden = true)
    protected transient OptContext optContext;

    public Class<?> getIdType() {
        return getGenericClass(null,0);
    }
}
``` 
这是子类，复用父类的字段
```java
/**
 * @author daizhong.liu
 * @description TODO
 * @date 2023/3/15 0015 9:22
 */
//@ApiModel("事例模型")
@Schema(description="事例模型")
@Data
@EqualsAndHashCode(callSuper = true)
@Builder
@NoArgsConstructor
@AllArgsConstructor
@TableName(value = "example", autoResultMap = true)
public class Example extends DefaultBaseModel {
//    @ApiModelProperty(value = "事例名称", required = true)
    @ApiModelGroup({"create","read","modify","delete"})
    @Schema(description="事例名称",required = true)
    private String name;
//    @ApiModelProperty(value = "备注")
    @ApiModelGroup({"create","read","modify","delete"})
    @Schema(description="备注")
    private String remarks;
//    @ApiModelProperty(value = "失效时间")
    @ApiModelGroup({"create","read","modify","delete"})
    @Schema(description="失效时间")
    private LocalDateTime expiryDate;
}
``` 
这是通用父类的接口定义
```java
@RestController
public interface BaseController<ID extends Serializable,E extends BaseModel<ID>,S extends CrudService<ID,E>> extends GenericTypeHelper {
    /**
     * 根据条件分页查询
     * @param entity 查询对象
     **/
//    @ApiOperation("根据条件分页查找")
    @Operation(summary = "根据条件分页查找")
    @PostMapping(path="/page")
    @ApiResponseGroup({"read","page"})
    @ApiOperationSupport(ignoreParameters = {"creator","createTime","updater","updateTime"})
    PageResult<E> findPage(@ApiGroup("read") @RequestBody(required = false)  E entity);

    /**
     * 根据ID查询
     * @param id 主键
     * @return
     **/
//    @ApiOperation("根据主键ID查找单实体")
    @Operation(summary = "根据主键ID查找单实体")
    @GetMapping(path="/{id}")
    @ApiResponseGroup("read")
    @ApiOperationSupport(ignoreParameters = {"creator","createTime","updater","updateTime","pageParam"})
    E get(@Parameter(name="id",description = "主键") @PathVariable("id") ID id);

    /**
     * 根据条件查询列表
     * @param entity 查询对象
     * @return 实体列表信息
     **/
//    @ApiOperation("根据条件查询列表")
    @Operation(summary = "根据条件查询列表")
    @PostMapping(path="/list")
    @ApiResponseGroup("read")
    @ApiOperationSupport(ignoreParameters = {"creator","createTime","updater","updateTime","pageParam"})
    List<E> find(@ApiGroup("read") @RequestBody(required = false) E entity);

    /**
     * 保存module
     * @param entity
     **/
//    @ApiOperation("新增实体")
    @Operation(summary = "新增实体")
    @PostMapping
    @ApiOperationSupport(ignoreParameters = {"id","tenantId","creator","createTime","updater","updateTime","pageParam"})
    void add(@ApiGroup("create") @RequestBody @Validated E entity);

    /**
     * 修改样例服务
     * @author daizhong.liu
     * @date 2020-09-29 15:28:21
     * @param entity
     * @return
     **/
//    @ApiOperation("修改实体")
    @Operation(summary = "修改实体")
    @PutMapping(path="/{id}",produces = "application/json;charset=UTF-8")
    @ApiOperationSupport(ignoreParameters = {"tenantId","creator","createTime","updater","updateTime","pageParam"})
    void modify(@ApiGroup("modify") @Parameter(name="id",description = "主键") @PathVariable("id") ID id, @RequestBody @Validated E entity);

    /**
     * 根据id逻辑删除样例服务
     * @author daizhong.liu
     * @date 2020-09-29 15:28:21
     * @param id 主键
     * @return
     **/
//    @ApiOperation("根据ID删除")
    @Operation(summary = "根据ID删除")
    @DeleteMapping(path="{id}")
    void remove(@Parameter(name="id",description = "主键") @PathVariable("id") ID id);

    default Class<?> getIdGenericClass() {
        return getGenericClass(null,0);
    }

    default Class<?> getEntityGenericClass() {
        return getGenericClass(null,1);
    }

    default Class<?> getServiceGenericClass() {
        return getGenericClass(null,2);
    }
}
```

**Comment by yoin528** [comment]
> > 具体代码贴一下呢？写个demo也行，之前我没用过
> 
> 这是父类，做通用增删改查用的
> 
> ```java
> package com.littora.basic.model;
> 
> import com.baomidou.mybatisplus.annotation.*;
> import com.littora.basic.model.group.annotation.ApiModelGroup;
> import com.littora.basic.model.pojo.PageParam;
> import io.swagger.v3.oas.annotations.media.Schema;
> import lombok.Data;
> 
> import java.io.Serializable;
> import java.time.LocalDateTime;
> 
> @Data
> public class BaseModel<ID extends Serializable> implements GenericTypeHelper,Serializable {
>     /**
>      * 主键
>      */
>     @TableId
>     @ApiModelGroup({"read","modify","delete"})
> //    @ApiModelProperty(value = "主键ID", example = "1")
>     @Schema(description="主键ID")
>     protected ID id;// 禁止使用0作为主键
>     /**
>      * 多租户编号
>      */
>     @TableField(fill = FieldFill.INSERT)
>     @ApiModelGroup({"read","modify","delete"})
> //    @ApiModelProperty(value = "租户ID", example = "1")
>     @Schema(description="租户ID")
>     protected ID tenantId;
>     /**
>      * 创建者，目前使用 SysUser 的 id 编号
>      */
>     @TableField(fill = FieldFill.INSERT)
>     @ApiModelGroup({"creater"})
> //    @ApiModelProperty(value = "创建者ID")
>     @Schema(description="创建者ID")
>     protected ID creator;
>     /**
>      * 创建时间
>      */
>     @TableField(fill = FieldFill.INSERT)
>     @ApiModelGroup({"creater"})
> //    @ApiModelProperty(value = "创建时间")
>     @Schema(description="创建时间")
>     protected LocalDateTime createTime;
>     /**
>      * 更新者，目前使用 SysUser 的 id 编号
>      */
>     @TableField(fill = FieldFill.INSERT_UPDATE)
>     @ApiModelGroup({"updater"})
> //    @ApiModelProperty(value = "修改者")
>     @Schema(description="修改者")
>     protected ID updater;
>     /**
>      * 最后更新时间
>      */
>     @TableField(fill = FieldFill.INSERT_UPDATE)
>     @ApiModelGroup({"updater"})
> //    @ApiModelProperty(value = "修改时间")
>     @Schema(description="修改时间")
>     protected LocalDateTime updateTime;
>     /**
>      * 数据版本,用于乐观锁
>      **/
>     @TableField
>     @Version
>     @ApiModelGroup({"version"})
> //    @ApiModelProperty(value = "数据版本")
>     @Schema(description="数据版本",hidden = true)
>     protected Long dataVersion;
>     /**
>      * 是否删除
>      */
>     @TableLogic
>     @ApiModelGroup({"deleted"})
> //    @ApiModelProperty(value = "逻辑删除标志，0：逻辑未删除，1：逻辑已删除")
>     @Schema(description="逻辑删除标志",hidden = true)
>     protected Boolean deleted = false;
>     /**
>      * 分页对象，不入库
>      **/
>     @TableField(exist = false)
>     @ApiModelGroup({"page"})
> //    @ApiModelProperty(value = "分页参数")
>     @Schema(description="分页参数")
>     protected PageParam pageParam;
>     /**
>      * 当前操作上下文，不入库
>      **/
>     @TableField(exist = false)
>     @ApiModelGroup({"context"})
>     @Schema(hidden = true)
>     protected transient OptContext optContext;
> 
>     public Class<?> getIdType() {
>         return getGenericClass(null,0);
>     }
> }
> ```
> 
> 这是子类，复用父类的字段
> 
> ```java
> /**
>  * @author daizhong.liu
>  * @description TODO
>  * @date 2023/3/15 0015 9:22
>  */
> //@ApiModel("事例模型")
> @Schema(description="事例模型")
> @Data
> @EqualsAndHashCode(callSuper = true)
> @Builder
> @NoArgsConstructor
> @AllArgsConstructor
> @TableName(value = "example", autoResultMap = true)
> public class Example extends DefaultBaseModel {
> //    @ApiModelProperty(value = "事例名称", required = true)
>     @ApiModelGroup({"create","read","modify","delete"})
>     @Schema(description="事例名称",required = true)
>     private String name;
> //    @ApiModelProperty(value = "备注")
>     @ApiModelGroup({"create","read","modify","delete"})
>     @Schema(description="备注")
>     private String remarks;
> //    @ApiModelProperty(value = "失效时间")
>     @ApiModelGroup({"create","read","modify","delete"})
>     @Schema(description="失效时间")
>     private LocalDateTime expiryDate;
> }
> ```
> 
> 这是通用父类的接口定义
> 
> ```java
> @RestController
> public interface BaseController<ID extends Serializable,E extends BaseModel<ID>,S extends CrudService<ID,E>> extends GenericTypeHelper {
>     /**
>      * 根据条件分页查询
>      * @param entity 查询对象
>      **/
> //    @ApiOperation("根据条件分页查找")
>     @Operation(summary = "根据条件分页查找")
>     @PostMapping(path="/page")
>     @ApiResponseGroup({"read","page"})
>     @ApiOperationSupport(ignoreParameters = {"creator","createTime","updater","updateTime"})
>     PageResult<E> findPage(@ApiGroup("read") @RequestBody(required = false)  E entity);
> 
>     /**
>      * 根据ID查询
>      * @param id 主键
>      * @return
>      **/
> //    @ApiOperation("根据主键ID查找单实体")
>     @Operation(summary = "根据主键ID查找单实体")
>     @GetMapping(path="/{id}")
>     @ApiResponseGroup("read")
>     @ApiOperationSupport(ignoreParameters = {"creator","createTime","updater","updateTime","pageParam"})
>     E get(@Parameter(name="id",description = "主键") @PathVariable("id") ID id);
> 
>     /**
>      * 根据条件查询列表
>      * @param entity 查询对象
>      * @return 实体列表信息
>      **/
> //    @ApiOperation("根据条件查询列表")
>     @Operation(summary = "根据条件查询列表")
>     @PostMapping(path="/list")
>     @ApiResponseGroup("read")
>     @ApiOperationSupport(ignoreParameters = {"creator","createTime","updater","updateTime","pageParam"})
>     List<E> find(@ApiGroup("read") @RequestBody(required = false) E entity);
> 
>     /**
>      * 保存module
>      * @param entity
>      **/
> //    @ApiOperation("新增实体")
>     @Operation(summary = "新增实体")
>     @PostMapping
>     @ApiOperationSupport(ignoreParameters = {"id","tenantId","creator","createTime","updater","updateTime","pageParam"})
>     void add(@ApiGroup("create") @RequestBody @Validated E entity);
> 
>     /**
>      * 修改样例服务
>      * @author daizhong.liu
>      * @date 2020-09-29 15:28:21
>      * @param entity
>      * @return
>      **/
> //    @ApiOperation("修改实体")
>     @Operation(summary = "修改实体")
>     @PutMapping(path="/{id}",produces = "application/json;charset=UTF-8")
>     @ApiOperationSupport(ignoreParameters = {"tenantId","creator","createTime","updater","updateTime","pageParam"})
>     void modify(@ApiGroup("modify") @Parameter(name="id",description = "主键") @PathVariable("id") ID id, @RequestBody @Validated E entity);
> 
>     /**
>      * 根据id逻辑删除样例服务
>      * @author daizhong.liu
>      * @date 2020-09-29 15:28:21
>      * @param id 主键
>      * @return
>      **/
> //    @ApiOperation("根据ID删除")
>     @Operation(summary = "根据ID删除")
>     @DeleteMapping(path="{id}")
>     void remove(@Parameter(name="id",description = "主键") @PathVariable("id") ID id);
> 
>     default Class<?> getIdGenericClass() {
>         return getGenericClass(null,0);
>     }
> 
>     default Class<?> getEntityGenericClass() {
>         return getGenericClass(null,1);
>     }
> 
>     default Class<?> getServiceGenericClass() {
>         return getGenericClass(null,2);
>     }
> }
> ```
这是通用父类的抽象实现
```java
public class AbstractBaseController<ID extends Serializable,E extends BaseModel<ID>,S extends CrudService<ID,E>> implements BaseController<ID,E,S>{
    @Autowired
    protected S service;

    @Override
    public PageResult<E> findPage(E entity) {
        return service.findPage(entity);
    }

    @Override
    public E get(ID id) {
        return service.findById(id);
    }

    @Override
    public List<E> find(E entity) {
        return service.findList(entity);
    }

    @Override
    public void add(E entity) {
        service.add(entity);
    }

    @Override
    public void modify(ID id, E entity) {
        entity.setId(id);
        service.modify(entity);
    }

    @Override
    public void remove(ID id) {
        service.remove(id);
    }
}
``` 
这是具体业务
```java
/**
 * ExampleController
 * @desc 案例
 * @date 2020-09-29 17:23:59
 * @author daizhong.liu
 */
//@Api(tags = "管理后台-事例")
@Tag(name = "example",description = "管理后台-事例")
@RestController
@RequestMapping(path = "/example")
public class ExampleController extends DefaultBaseController<Example, ExampleService> {
}
```

**Comment by yoin528** [comment]
我搞了个框架想做技术中台与数据中台，将通用的增删改查复用起来，但又要去掉的DTO，VO，QO，PO这些重复的POJO，又怕泄露不该显示的字段信息，所以找到你写的这个，在这之前其实有搞过事前进行Bean的处理，但效果不好，后面你这个方案能完成90%的业务，但由于通用性，就涉及到泛型，导致有些业务处理不了，而且后面这个框架一旦升级就有更多的兼容要做，所以我觉得还是事前比较好，目前我找到一个使用javassist字节码将原生类型根据分组进行生成新的Class的方案应该可行，现在正在封装。

**Comment by JYHarvest** [comment]
嗯，你先试试你找的字节码方式，我看看你说的问题有没有搞头

**Comment by yoin528** [comment]
> 嗯，你先试试你找的字节码方式，我看看你说的问题有没有搞头

已经可以了，我现在使用的swagger3+knife4j，虽然knife4j也有过滤的，但有bug，官方也有人提过issue，但作者好像不维护这个问题了，我处理完实际返回json时根据swagger显示的过滤不要的字段后再提一版这个框架的过来。

问下，你了解过混合云架构么，钉钉好像就是使用混合云架构的，有没有这种方案的资料？我说的架构实现，我想后面的框架扩展混合云的实现。

**Comment by JYHarvest** [comment]
不了解







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JYHarvest/springfox3-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 中午12:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JYHarvest/springfox3-plus] 关于使用泛型后无法根据分组进行分类显示的问题 (Issue #2)





  
嗯，你先试试你找的字节码方式，我看看你说的问题有没有搞头
  
已经可以了，我现在使用的swagger3+knife4j，虽然knife4j也有过滤的，但有bug，官方也有人提过issue，但作者好像不维护这个问题了，我处理完实际返回json时根据swagger显示的过滤不要的字段后再提一版这个框架的过来。
 
问下，你了解过混合云架构么，钉钉好像就是使用混合云架构的，有没有这种方案的资料？我说的架构实现，我想后面的框架扩展混合云的实现。

**Comment by JYHarvest** [comment]
兄弟已有其它方案，结案

**Comment by yoin528** [comment]
你其它啥方案，我这边已经实现技术方案的可行性，但还没整体流程处理完，后面工作忙，框架前端vue还在整，等处理完这些再整。
