### ISSUE TITLE
SpringFoxRequest 添加get/set方法后，启动后访问文档会报错

### ISSUE THREAD

**Issue by chengshuanghui** [JYHarvest/springfox3-plus#3]

**Comment by JYHarvest** [comment]
感谢反馈，我来定位一下，或者你也可以提pr



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chengshuanghui ***@***.***&gt;
发送时间: 2023年5月26日 11:56
收件人: JYHarvest/springfox3-plus ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [JYHarvest/springfox3-plus] SpringFoxRequest 添加get/set方法后，启动后访问文档会报错 (Issue #3)

**Comment by JYHarvest** [comment]
已修复，谢谢
